# Generated by Django 5.1.6 on 2025-02-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_per_unit',
            field=models.BooleanField(default=False, help_text='Indicates if the price is per unit (e.g., tablet, ampoule) or for the full product.'),
        ),
    ]
